### ISSUE TITLE
Magento 2 version?

### ISSUE THREAD

**Issue by cscd98** [yireo/Yireo_DisableLog#1]
Do you have any plans? Thanks

**Comment by yireo** [comment]
Yes, we are working on migrating all Magento 1 extensions to Magento 2, and once we have news we will definitely communicate this via our site. So stay tuned on our Yireo site, not this issue tracker, because there is no issue yet to report :)

**Comment by cscd98** [comment]
@yireo Any updates, it's been quite a while!

**Comment by jissereitsma** [comment]
Unfortunately this means that we are very busy with things: https://www.yireo.com/magento2

**Comment by jissereitsma** [comment]
See https://github.com/yireo/Yireo_DisableLog2

**Comment by cscd98** [comment]
@jissereitsma Thank you 👍
