### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by kweij** [yireo/Yireo_DisableLog#2]
Hi Yireo/Jisse,

Would you be so kind to tag the latest changes into a new 0.0.7 release?

Thanks in advance,
Klaas

**Comment by yireo** [comment]
Done

**Comment by kweij** [comment]
Dude, fast!

**Comment by jhoelzl** [comment]
Please also adjust the Magento module version in config.xml to 0.0.7. Thanks!

**Comment by yireo** [comment]
It seems we have an issue in our automatic release system, that causes the XML config to be pushed to GitHub before GitHub is being asked to build a new tag-based release. We will fix this in the next release.

**Comment by jissereitsma** [comment]
This is now done automatically for every proper release.
