### ISSUE TITLE
Observer class name error in XML

### ISSUE THREAD

**Issue by aurmil** [yireo/Yireo_DisableLog#4]
Warning: get_class() expects parameter 1 to be object, boolean given  in /app/code/core/Mage/Core/Model/App.php on line 1360

problem is at https://github.com/yireo/Yireo_DisableLog/blob/master/source/app/code/community/Yireo/DisableLog/etc/config.xml#L125
class name should be Yireo_DisableLog_Model_Feed

**Comment by jissereitsma** [comment]
Are you sure? The class `Yireo_DisableLog_Model_Feed` is not an observer and it does not contain a method `controllerActionPredispatch`. Instead the method is contained in the class `Yireo_DisableLog_Observer_Feed` which is indeed an observer and which is calling upon the other model. Could it be that the file `Observer/Feed.php` is missing in your installation?

**Comment by aurmil** [comment]
I don't have a Yireo_DisableLog_Observer_Feed class in my version, have Yireo_DisableLog_Model_Feed and Yireo_DisableLog_Model_Observer

**Comment by jissereitsma** [comment]
Thanks. So #3 mentions the solution. See also the latest release.

**Comment by aurmil** [comment]
OK, thank you
